import { createApp } from 'vue'
import axios from 'axios'
import './style.css'

const api = axios.create({ baseURL: '/api/' })
api.interceptors.request.use(config => { const token = localStorage.getItem('spmp-token'); if (token) config.headers.Authorization = `Bearer ${token}`; return config })

createApp({
  data() { return {
    token: localStorage.getItem('spmp-token') || '', user: null, error: '', notice: '', active: 'dashboard',
    loginForm: { username: 'admin', password: '' }, hosts: [], packages: [], deployments: [], logs: [], selectedDeployment: null,
    hostForm: { name: '', address: '', ssh_port: 22, ssh_user: 'root', ssh_private_key: '', os_family: 'Rocky', os_version: '9', architecture: 'x86_64' },
    packageForm: { version: '6.2.17', file: null }, tenantForm: { name: '' }, userForm: { username: '', password: '', tenant_id: '', role: 'tenant_admin' },
    deployForm: { name: '', package_id: '', node_ids: [], replicas: 1, redis_port: 6379, install_dir: '/opt/middleware/redis', data_dir: '/data/redis', log_dir: '/var/log/middleware/redis', config_dir: '/etc/middleware/redis', redis_password: '', maxmemory: '', maxmemory_policy: 'noeviction', appendonly: true, custom_redis_conf: '' }
  } },
  computed: {
    isAdmin() { return this.user?.role === 'super_admin' },
    isOperator() { return ['super_admin', 'tenant_admin', 'operator'].includes(this.user?.role) },
    selectedHosts() { return this.hosts.filter(h => this.deployForm.node_ids.includes(h.id)) }
  },
  methods: {
    async request(method, url, body, config) { try { const { data } = await api.request({ method, url, data: body, ...config }); return data } catch (e) { this.error = e.response?.data?.detail || e.message; throw e } },
    async login() { this.error = ''; try { const data = await this.request('post', 'auth/login', this.loginForm); this.token = data.access_token; localStorage.setItem('spmp-token', this.token); this.user = data.user; await this.refresh() } catch {} },
    logout() { localStorage.removeItem('spmp-token'); this.token = ''; this.user = null },
    async refresh() { if (!this.token) return; try { this.user = await this.request('get', 'me'); await Promise.all([this.loadHosts(), this.loadPackages(), this.loadDeployments()]) } catch { this.logout() } },
    async loadHosts() { this.hosts = await this.request('get', 'hosts') },
    async loadPackages() { this.packages = await this.request('get', 'packages'); if (!this.deployForm.package_id && this.packages.length) this.deployForm.package_id = this.packages[0].id },
    async loadDeployments() { this.deployments = await this.request('get', 'deployments') },
    async createHost() { const data = await this.request('post', 'hosts', this.hostForm); this.hosts.unshift(data); this.notice = '服务器资产已保存（私钥已加密）。'; this.hostForm = { ...this.hostForm, name: '', address: '', ssh_private_key: '' } },
    async uploadPackage() { if (!this.packageForm.file) { this.error = '请选择 Redis 源码包'; return } const form = new FormData(); form.append('file', this.packageForm.file); const data = await this.request('post', `packages/redis?version=${encodeURIComponent(this.packageForm.version)}`, form); this.packages.unshift(data); this.deployForm.package_id = data.id; this.notice = 'Redis 软件包上传成功。' },
    chooseFile(e) { this.packageForm.file = e.target.files[0] },
    toggleNode(id) { const list = this.deployForm.node_ids; const i = list.indexOf(id); i >= 0 ? list.splice(i, 1) : list.push(id) },
    async createDeployment() { this.error = ''; const config = { ...this.deployForm }; delete config.name; delete config.package_id; config.maxmemory = config.maxmemory || null; config.custom_redis_conf = config.custom_redis_conf || null; try { const data = await this.request('post', 'deployments/redis', { name: this.deployForm.name, package_id: this.deployForm.package_id, config }); this.deployments.unshift(data); this.notice = '任务已提交，Worker 将先做编译依赖和冲突预检。'; this.active = 'tasks' } catch {} },
    async showLogs(task) { this.selectedDeployment = task; this.logs = await this.request('get', `deployments/${task.id}/logs`); },
    async retry(task) { await this.request('post', `deployments/${task.id}/retry`); this.notice = '重试任务已创建。'; await this.loadDeployments() },
    async createTenant() { const item = await this.request('post', 'admin/tenants', this.tenantForm); this.userForm.tenant_id = item.id; this.tenantForm.name = ''; this.notice = `租户 ${item.name} 已创建，请创建租户管理员。` },
    async createUser() { await this.request('post', 'admin/users', this.userForm); this.notice = '用户创建成功。'; this.userForm.username = ''; this.userForm.password = '' },
  },
  mounted() { this.refresh() },
  template: `
  <main v-if="!token" class="login-shell"><section class="login-card"><div class="brand-mark">SP</div><h1>SP MediDeploy</h1><p>安全、可追溯的离线中间件部署平台</p><form @submit.prevent="login"><label>用户名<input v-model="loginForm.username" autocomplete="username" /></label><label>密码<input v-model="loginForm.password" type="password" autocomplete="current-password" autofocus /></label><button>登录平台</button></form><small>首次密码由 SPMP_BOOTSTRAP_PASSWORD 配置。</small><p v-if="error" class="error">{{error}}</p></section></main>
  <main v-else class="app-shell"><aside><div class="brand"><span>SP</span><div><strong>SP MediDeploy</strong><small>Middleware Platform</small></div></div><nav><button v-for="item in [{id:'dashboard',label:'概览'},{id:'hosts',label:'服务器资产'},{id:'packages',label:'软件包'},{id:'redis',label:'Redis Cluster'},{id:'tasks',label:'部署任务'},...(isAdmin?[{id:'admin',label:'平台管理'}]:[])]" :class="{active:active===item.id}" @click="active=item.id">{{item.label}}</button></nav><div class="profile"><b>{{user.username}}</b><span>{{user.role}}</span><a @click="logout">退出</a></div></aside><section class="content"><header><div><h1>{{{dashboard:'运行概览',hosts:'服务器资产',packages:'离线软件包',redis:'创建 Redis Cluster',tasks:'部署任务',admin:'平台管理'}[active]}}</h1><p>SPMP · {{ user.tenant_id ? '租户隔离已启用' : '平台级管理员' }}</p></div><button class="secondary" @click="refresh">刷新数据</button></header><p v-if="notice" class="notice">{{notice}}</p><p v-if="error" class="error">{{error}}</p>
  <section v-if="active==='dashboard'" class="dashboard"><article><span>服务器</span><strong>{{hosts.length}}</strong><small>当前租户可用资产</small></article><article><span>软件包</span><strong>{{packages.length}}</strong><small>已上传的 Redis 源码包</small></article><article><span>任务</span><strong>{{deployments.length}}</strong><small>含历史部署与重试</small></article><article><span>部署前必检</span><strong>6</strong><small>Python、编译工具、sudo、systemd 等</small></article><div class="panel wide"><h2>使用流程</h2><ol><li>平台管理员创建租户和租户管理员。</li><li>租户管理员登记服务器，再上传 Redis 源码包。</li><li>创建集群任务。所有目标主机首先执行预检，任一失败均不开始部署。</li><li>失败时按本次任务资源清单自动回滚；可查看日志后重试。</li></ol></div></section>
  <section v-if="active==='hosts'" class="two-col"><form class="panel form" @submit.prevent="createHost"><h2>登记服务器</h2><label>名称<input v-model="hostForm.name" required placeholder="redis-node-01"/></label><label>IP 或主机名<input v-model="hostForm.address" required placeholder="10.0.0.11"/></label><div class="row"><label>SSH 端口<input v-model.number="hostForm.ssh_port" type="number" required/></label><label>SSH 用户<input v-model="hostForm.ssh_user" required/></label></div><div class="row"><label>系统<select v-model="hostForm.os_family"><option>openEuler</option><option>银河麒麟 V10 SP3</option><option>Rocky</option><option>Ubuntu</option><option>CentOS</option></select></label><label>版本<input v-model="hostForm.os_version"/></label></div><label>SSH 私钥<textarea v-model="hostForm.ssh_private_key" required placeholder="-----BEGIN OPENSSH PRIVATE KEY-----"></textarea></label><button v-if="isOperator">加密保存资产</button><p v-else class="muted">只读审计角色不可写入。</p></form><div class="panel"><h2>已登记服务器</h2><table><thead><tr><th>名称</th><th>地址</th><th>系统</th><th>架构</th></tr></thead><tbody><tr v-for="h in hosts"><td>{{h.name}}</td><td>{{h.address}}:{{h.ssh_port}}</td><td>{{h.os_family}} {{h.os_version}}</td><td>{{h.architecture}}</td></tr><tr v-if="!hosts.length"><td colspan="4" class="muted">尚无服务器资产</td></tr></tbody></table></div></section>
  <section v-if="active==='packages'" class="two-col"><form class="panel form" @submit.prevent="uploadPackage"><h2>上传 Redis 源码包</h2><p class="muted">仅 `.tar.gz` 或 `.tgz`；上传后保存在平台 Docker 持久卷，无需人工放到服务器目录。</p><label>Redis 版本<input v-model="packageForm.version" required placeholder="6.2.17"/></label><label>源码包<input type="file" accept=".tar.gz,.tgz" @change="chooseFile" required/></label><button v-if="isOperator">上传并校验 SHA-256</button></form><div class="panel"><h2>软件包库</h2><table><thead><tr><th>版本</th><th>文件</th><th>SHA-256</th><th>架构</th></tr></thead><tbody><tr v-for="p in packages"><td>{{p.version}}</td><td>{{p.filename}}</td><td class="hash">{{p.sha256}}</td><td>{{p.architecture}}</td></tr><tr v-if="!packages.length"><td colspan="4" class="muted">请先上传 Redis 6.2.17 源码包</td></tr></tbody></table></div></section>
  <section v-if="active==='redis'" class="panel form deployment-form"><h2>部署参数</h2><p class="muted">所有目录必须不存在；系统将拒绝覆盖路径、服务名和端口。自定义 redis.conf 具有最高优先级。</p><div class="row"><label>部署名称<input v-model="deployForm.name" required placeholder="production-redis"/></label><label>源码包<select v-model="deployForm.package_id" required><option disabled value="">选择已上传版本</option><option v-for="p in packages" :value="p.id">Redis {{p.version}} · {{p.filename}}</option></select></label></div><h3>选择节点（至少 3 个）</h3><div class="host-picker"><label v-for="h in hosts" :class="{picked:deployForm.node_ids.includes(h.id)}"><input type="checkbox" :checked="deployForm.node_ids.includes(h.id)" @change="toggleNode(h.id)"/> <b>{{h.name}}</b><span>{{h.address}}</span></label><p v-if="!hosts.length" class="muted">请先登记服务器。</p></div><div class="row"><label>副本数<select v-model.number="deployForm.replicas"><option :value="0">0（无副本）</option><option :value="1">1（推荐）</option><option :value="2">2</option></select></label><label>Redis 端口<input v-model.number="deployForm.redis_port" type="number" min="1024" max="65535"/></label><label>Redis 密码<input v-model="deployForm.redis_password" type="password" required minlength="8"/></label></div><div class="grid4"><label>安装目录<input v-model="deployForm.install_dir"/></label><label>数据目录<input v-model="deployForm.data_dir"/></label><label>日志目录<input v-model="deployForm.log_dir"/></label><label>配置目录<input v-model="deployForm.config_dir"/></label></div><div class="row"><label>AOF<select v-model="deployForm.appendonly"><option :value="true">开启</option><option :value="false">关闭</option></select></label><label>最大内存<input v-model="deployForm.maxmemory" placeholder="例如 8gb（可选）"/></label><label>淘汰策略<select v-model="deployForm.maxmemory_policy"><option>noeviction</option><option>allkeys-lru</option><option>volatile-lru</option><option>allkeys-lfu</option></select></label></div><label>自定义 redis.conf（可选，填写后将完全覆盖默认配置）<textarea v-model="deployForm.custom_redis_conf" rows="10" placeholder="port 6379&#10;cluster-enabled yes&#10;..."></textarea></label><button @click="createDeployment" :disabled="!isOperator">提交部署任务</button></section>
  <section v-if="active==='tasks'" class="panel"><h2>任务与审计日志</h2><table><thead><tr><th>任务</th><th>状态</th><th>创建时间</th><th>操作</th></tr></thead><tbody><tr v-for="task in deployments"><td><b>{{task.name}}</b><small>{{task.id}}</small></td><td><span class="status" :class="task.status">{{task.status}}</span></td><td>{{new Date(task.created_at).toLocaleString()}}</td><td><button class="link" @click="showLogs(task)">日志</button><button v-if="['failed','rolled_back'].includes(task.status) && isOperator" class="link" @click="retry(task)">重试</button></td></tr></tbody></table><div v-if="selectedDeployment" class="logs"><div><h3>{{selectedDeployment.name}} 日志</h3><button class="link" @click="showLogs(selectedDeployment)">刷新</button></div><pre v-for="line in logs">[{{new Date(line.created_at).toLocaleTimeString()}}] {{line.level}} {{line.message}}</pre></div></section>
  <section v-if="active==='admin'" class="two-col"><form class="panel form" @submit.prevent="createTenant"><h2>创建租户</h2><label>租户名称<input v-model="tenantForm.name" required placeholder="生产环境团队"/></label><button>创建租户</button></form><form class="panel form" @submit.prevent="createUser"><h2>创建本地用户</h2><p class="muted">创建租户后复制返回的租户 ID 填入下方；首期保持最小化管理界面。</p><label>用户名<input v-model="userForm.username" required/></label><label>密码<input v-model="userForm.password" type="password" required/></label><label>租户 ID<input v-model="userForm.tenant_id" required/></label><label>角色<select v-model="userForm.role"><option value="tenant_admin">tenant_admin</option><option value="operator">operator</option><option value="auditor">auditor</option></select></label><button>创建用户</button></form></section>
  </section></main>`
}).mount('#app')
